*** Variables ***

### GLOBAL VARIABLES ###
${url}                          https://www.amaysim.com.au/my-account/my-amaysim/services
${browser}                      chrome
${usageHistory_url}             https://www.amaysim.com.au/my-account/my-amaysim/usage_records
${managePlan_url}               https://www.amaysim.com.au/my-account/my-amaysim/products
${personalDetails_url}          https://www.amaysim.com.au/my-account/my-amaysim/personal-details
${settings_url}                 https://www.amaysim.com.au/my-account/my-amaysim/settings

### LOGIN CREDENTIALS ###
${username}                     0466134574
${password}                     AWqasde321